PodTemplate.dockerTemplate {
    node(POD_LABEL) {
        container('docker') {
            sh 'echo hello from $POD_CONTAINER'
            sh 'docker info'
        }
    }
}

// pipeline {
//     agent {
//         kubernetes {
//             yaml """
// apiVersion: v1
// kind: Pod
// spec:
//     containers:
//     - name: docker
//       image: docker:latest
//       imagePullPolicy: Always
//       command: ["cat"]
//       tty: true
//       volumeMounts:
//         - name: docker-sock
//           hostPath: /var/run/docker.sock
// """
//         }
//     }
//     stages {
//         stage('Build') {
//             steps {
//                 container('docker') {
//                     sh 'docker info'
//                 }
//             }
//         }
//     }
// }
